import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useAppContext } from '../context/AppContext';
import type { RootStackParamList } from '../navigation/MainNavigator';

type Props = NativeStackScreenProps<RootStackParamList, 'ClueCatchResult'>;

export function ClueCatchResultScreen({ navigation, route }: Props) {
  const { bestClueCatchScore } = useAppContext();
  const { score, mistakes, evidence } = route.params;
  return <View style={styles.container}><Text style={styles.eyebrow}>CASE CLOSED</Text><Text style={styles.score}>{score.toLocaleString()}</Text><Text style={styles.label}>FINAL SCORE</Text>{score >= bestClueCatchScore ? <Text style={styles.badge}>★ NEW BEST RECORD</Text> : null}<View style={styles.stats}><View style={[styles.stat, styles.statGreen]}><Text style={[styles.statValue, { color: '#4ed57b' }]}>{evidence}</Text><Text style={styles.statLabel}>EVIDENCE</Text></View><View style={[styles.stat, styles.statRed]}><Text style={[styles.statValue, { color: '#ff9d90' }]}>{mistakes}</Text><Text style={styles.statLabel}>MISTAKES</Text></View><View style={[styles.stat, styles.statGold]}><Text style={[styles.statValue, { color: '#ffc21c' }]}>{bestClueCatchScore.toLocaleString()}</Text><Text style={styles.statLabel}>BEST</Text></View></View><Pressable style={styles.playAgain} onPress={() => navigation.replace('ClueCatchGame')}><Text style={styles.playAgainText}>Play Again</Text></Pressable><Pressable style={styles.backButton} onPress={() => navigation.navigate('Tabs', { screen: 'ClueCatch' })}><Text style={styles.backButtonText}>Back to Menu</Text></Pressable></View>;
}

const styles = StyleSheet.create({container:{flex:1,backgroundColor:'#dff6ff',justifyContent:'center',paddingHorizontal:22},eyebrow:{color:'#0f87b8',fontSize:12,letterSpacing:4,fontWeight:'800',textAlign:'center',marginBottom:18},score:{color:'#12324a',fontSize:60,fontWeight:'900',textAlign:'center'},label:{color:'rgba(28,74,103,0.56)',textAlign:'center',letterSpacing:3,marginBottom:18},badge:{alignSelf:'center',backgroundColor:'#ffc21c',color:'#2c283b',paddingHorizontal:16,paddingVertical:8,borderRadius:14,fontSize:16,fontWeight:'900',marginBottom:30},stats:{flexDirection:'row',gap:10,marginBottom:28},stat:{flex:1,borderRadius:18,paddingVertical:18,alignItems:'center',borderWidth:1},statGreen:{backgroundColor:'#eefaff',borderColor:'rgba(57,208,123,0.28)'},statRed:{backgroundColor:'#fff1ef',borderColor:'rgba(255,83,53,0.24)'},statGold:{backgroundColor:'#f7fcff',borderColor:'rgba(255,194,28,0.28)'},statValue:{fontSize:24,fontWeight:'900',marginBottom:6},statLabel:{color:'rgba(28,74,103,0.72)',fontSize:12},playAgain:{height:58,borderRadius:18,backgroundColor:'#ffc21c',alignItems:'center',justifyContent:'center',marginBottom:12},playAgainText:{color:'#20253a',fontSize:18,fontWeight:'800'},backButton:{height:54,borderRadius:18,borderWidth:1,borderColor:'rgba(15,135,184,0.18)',alignItems:'center',justifyContent:'center'},backButtonText:{color:'#12324a',fontSize:17,fontWeight:'800'}});
